# This file defines all the services and databases for the application.

# The 'databases' key is a top-level section for managed databases.
databases:
  - name: micro-merch-db
    plan: free # Use the free tier for the database
    databaseName: ecommerce_db # Optional: specify the initial DB name
    user: user # Optional: specify the initial user

services:
  # 1. The RabbitMQ Message Broker
  - type: pservice
    name: rabbitmq
    dockerimage: rabbitmq:3-management-alpine
    plan: free

  # 2. The Backend Web Services (Flask Apps)
  - type: web
    name: users-service
    plan: free
    env: docker
    dockerfilePath: ./users-service/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: micro-merch-db
          property: connectionString
      - key: FLASK_DEBUG
        value: 0

  - type: web
    name: products-service
    plan: free
    env: docker
    dockerfilePath: ./products-service/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: micro-merch-db
          property: connectionString
      - key: RABBITMQ_URL
        fromService:
          type: pservice
          name: rabbitmq
          property: host
      - key: FLASK_DEBUG
        value: 0

  - type: web
    name: orders-service
    plan: free
    env: docker
    dockerfilePath: ./orders-service/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: micro-merch-db
          property: connectionString
      - key: RABBITMQ_URL
        fromService:
          type: pservice
          name: rabbitmq
          property: host
      - key: USERS_SERVICE_URL
        fromService:
          type: web
          name: users-service
          property: url
      - key: PRODUCTS_SERVICE_URL
        fromService:
          type: web
          name: products-service
          property: url
      - key: FLASK_DEBUG
        value: 0

  # 3. The API Gateway Service
  - type: web
    name: api-gateway
    plan: free
    env: docker
    dockerfilePath: ./api-gateway/Dockerfile
    envVars:
      - key: USERS_SERVICE_URL
        fromService: { type: web, name: users-service, property: url }
      - key: PRODUCTS_SERVICE_URL
        fromService: { type: web, name: products-service, property: url }
      - key: ORDERS_SERVICE_URL
        fromService: { type: web, name: orders-service, property: url }
      - key: FRONTEND_URL
        fromService: { type: static, name: frontend-service, property: url }
      - key: FLASK_DEBUG
        value: 0

  # 4. The React Frontend
  - type: static
    name: frontend-service
    plan: free
    env: docker
    dockerfilePath: ./frontend-service/Dockerfile
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
